# Generated by Django 5.1.6 on 2025-06-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
    ]
